language: python

python:
  - "2.7"
  
env:
  global:
    - DB_HOST=127.0.0.1
    - DB_PORT=5432
    - DB_USER=postgres
    - DB_PASSWORD=none
    - DB_NAME=lg_prod

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install apache2
  - sudo apt-get install libapache2-mod-fcgid
  - sudo apt-get install libapache2-mod-xsendfile
  - sudo apt-get install libapache2-mod-wsgi
  - sudo apt-get install sendmail
  - sudo apt-get install libmail-sendmail-perl
  - sudo apt-get install python-software-properties
  - echo "yes" | sudo add-apt-repository ppa:ubuntugis/ppa
  - sudo apt-get update -qq
  - sudo apt-get install mapserver-bin
  - sudo apt-get install gdal-bin cgi-mapserver
  - sudo apt-get install python-gdal
  - sudo apt-get install python-mapscript
  - sudo apt-get install libcv2.3 libopencv-dev python-opencv

install: "pip install -r deploy_tools/requirements.txt"

before_script:
  - psql -c 'create database lg_prod;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d lg_prod
  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d lg_prod
  
script: ./deploy_tools/setup.sh