sudo: required
dist: trusty
language: python

python:
  - "2.7"
  
env:
  global:
    - DB_HOST=127.0.0.1
    - DB_PORT=5432
    - DB_USER=postgres
    - DB_PASSWORD=none
    - DB_NAME=lg_database
    - FILE_ROOT=$TRAVIS_BUILD_DIR

virtualenv:
  system_site_packages: true
  
addons:
  postgresql: "9.1"

services:
  - postgresql

before_install:
  - sudo apt-get update -qq
  # Uninstall the default postgres / postgis:
  # - sudo mv /etc/apt/sources.list.d/pgdg-source.list* /tmp
  # - sudo apt-get -y remove postgis libpq5 libpq-dev postgresql-9.1-postgis postgresql-9.2-postgis postgresql-9.3-postgis postgresql-9.1 postgresql-9.2 postgresql-9.3
  # - sudo apt-get -y remove libgdal1
  
  # Reference custom repo:
  - sudo apt-get -y install python-software-properties
  #- echo "yes" | sudo add-apt-repository ppa:ubuntugis/ppa
  #- sudo apt-get update -qq
  
  # Install GIS libraries
  - sudo apt-get -y install mapserver-bin
  - sudo apt-get -y install gdal-bin
  - sudo apt-get -y install cgi-mapserver
  
  # Install custom PostgreSQL / PostGIS
  - sudo apt-get -y install postgresql-9.1
  - sudo apt-get -y install postgresql-client-9.1
  - sudo apt-get -y install postgresql-server-dev-9.1
  - sudo apt-get -y install postgresql-plperl-9.1
  - sudo apt-get -y install postgresql-9.1-postgis-2.0
  
  # Install some final MapServer libraries (which I think need to 
  # get installed after PostgreSQL / PostGIS)
  - sudo apt-get -y install libmapserver1 libmapserver1-dev
  - sudo apt-get -y install python-gdal
  
  # Install Apache + Modules
  - sudo apt-get -y install apache2
  - sudo apt-get -y install libapache2-mod-fcgid
  - sudo apt-get -y install libapache2-mod-xsendfile
  - sudo apt-get -y install libapache2-mod-wsgi
  - sudo apt-get -y install sendmail
  - sudo apt-get -y install libmail-sendmail-perl

  # Install miscellaneous libraries for graphics, audio, etc.
  - sudo apt-get -y install libcv-dev libopencv-dev python-opencv
  - sudo apt-get -y install python-psycopg2
  - sudo apt-get -y install python-setuptools
  - sudo apt-get -y install python-pip=1.5.4-1ubuntu3
  - sudo apt-get -y install python-dev
  - sudo apt-get -y install python-mapscript
  - sudo apt-get -y install python-scipy
  - sudo add-apt-repository -y ppa:mc3man/trusty-media #trusty ubuntu doesn't have an ffmpeg package (only libav)
  - sudo apt-get -y update
  - sudo apt-get -y install ffmpeg
  - sudo apt-get -y install redis-server

install:
  - pip install -r deploy_tools/requirements.txt
#  - pip install PIL==1.1.7 --allow-external PIL --allow-unverified PIL
  - pip install Pillow #does this work the same as PIL?

before_script:
  - psql -c 'create database lg_database;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d lg_database
  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d lg_database
  - mkdir userdata
  - mkdir userdata/media
  - mkdir userdata/media/tester
  - mkdir userdata/media/tester/photos
  - mkdir userdata/media/tester/audio
  - mkdir userdata/prints
  - mkdir userdata/deleted
  - ./deploy_tools/gis.sh
  
script: cd apps && python manage.py test --verbosity=2
